### PR TITLE
Shorter version of hasSubsequence

### PR DESCRIPTION
**Pull request by ailveen**
Shorter version of hasSubsequence

### CODE REVIEW

**Comment by runarorama** [comment]
This implementation is incorrect. For example, it will return `false` for `hasSubsequence(List(1112),List(112))`. Or am I missing something?

**Comment by ailveen** [comment]
Maybe you meant hasSubsequence(List( 1, 1, 1, 2), List(1, 1, 2)). My unit tests passed on this with flying colors. Can you clarify yourself?

**Comment by runarorama** [comment]
OK, how about `hasSubsequence("11312".toList, "112".toList)`?

**Comment by runarorama** [comment]
Actually, the problem may be that this function is inappropriately named. What we're really asking for (and what the solution we give implements) is a _substring_, not a subsequence.

**Comment by runarorama** [comment]
https://github.com/fpinscala/fpinscala/issues/377

**Comment by ailveen** [comment]
I still don't understand how subsequence became substring here. The question seemed pretty clear to me when I did this. I guess I'm just learning functional programming and you're one of the admins here so you can do what you want.

This is the question, btw:

Hard: As an example, implement hasSubsequence for checking whether a List contains
another List as a subsequence. For instance, List(1,2,3,4) would have
List(1,2), List(2,3), and List(4) as subsequences, among others. You may have
some difficulty finding a concise purely functional implementation that is also efficient.
That’s okay. Implement the function however comes most naturally. We’ll
return to this implementation in chapter 5 and hopefully improve on it. Note: Any
two values x and y can be compared for equality in Scala using the expression x == y.

def hasSubsequence[A](sup: List[A], sub: List[A]): Boolean

**Comment by ailveen** [comment]
I think I understand what you mean now. List(1, 4) is a subsequence of List(1, 2, 3, 4) but is not a substring, A correct substring would be List(1, 2) [in correct order]. 

You were right to reject my version here.

**Pull request closed without merging**
